//
//  BidiGenerateContentServerMessage.swift
//  Sandcastle
//
//  Created by Leptos on 2/19/26.
//

import Foundation

/// Response message for the BidiGenerateContent call.
///
/// <https://ai.google.dev/api/live#bidigeneratecontentservermessage>
struct BidiGenerateContentServerMessage {
    enum Payload {
        /// Output only. Sent in response to a ``BidiGenerateContentSetup`` message from the client when setup is complete.
        case setupComplete(BidiGenerateContentSetupComplete)
        /// Output only. Content generated by the model in response to client messages.
        case serverContent(BidiGenerateContentServerContent)
        /// Output only. Request for the client to execute the functionCalls and return the responses with the matching ids.
        case toolCall(BidiGenerateContentToolCall)
        /// Output only. Notification for the client that a previously issued ToolCallMessage with the specified ids should be cancelled.
        case toolCallCancellation(BidiGenerateContentToolCallCancellation)
        /// Output only. A notice that the server will soon disconnect.
        case goAway(GoAway)
        /// Output only. Update of the session resumption state.
        case sessionResumptionUpdate(SessionResumptionUpdate)
    }
    
    /// Output only. Usage metadata about the response(s).
    let usageMetadata: UsageMetadata?
    /// The type of the message.
    let messageType: Payload
}

extension BidiGenerateContentServerMessage: Codable {
    enum CodingKeys: String, CodingKey {
        case usageMetadata
        
        // messageType
        case setupComplete
        case serverContent
        case toolCall
        case toolCallCancellation
        case goAway
        case sessionResumptionUpdate
    }
    
    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        self.usageMetadata = try container.decodeIfPresent(UsageMetadata.self, forKey: .usageMetadata)
        
        if let value = try container.decodeIfPresent(BidiGenerateContentSetupComplete.self, forKey: .setupComplete) {
            self.messageType = .setupComplete(value)
        } else if let value = try container.decodeIfPresent(BidiGenerateContentServerContent.self, forKey: .serverContent) {
            self.messageType = .serverContent(value)
        } else if let value = try container.decodeIfPresent(BidiGenerateContentToolCall.self, forKey: .toolCall) {
            self.messageType = .toolCall(value)
        } else if let value = try container.decodeIfPresent(BidiGenerateContentToolCallCancellation.self, forKey: .toolCallCancellation) {
            self.messageType = .toolCallCancellation(value)
        } else if let value = try container.decodeIfPresent(GoAway.self, forKey: .goAway) {
            self.messageType = .goAway(value)
        } else if let value = try container.decodeIfPresent(SessionResumptionUpdate.self, forKey: .sessionResumptionUpdate) {
            self.messageType = .sessionResumptionUpdate(value)
        } else {
            let allKeys: [CodingKeys] = [.setupComplete, .serverContent, .toolCall, .toolCallCancellation, .goAway, .sessionResumptionUpdate]
            let keysFormatted = allKeys
                .map { "'\($0.rawValue)'" }
                .joined(separator: ", ")
            throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Expected one of \(keysFormatted)"))
        }
    }
    
    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encodeIfPresent(usageMetadata, forKey: .usageMetadata)
        
        switch messageType {
        case .setupComplete(let value):
            try container.encode(value, forKey: .setupComplete)
        case .serverContent(let value):
            try container.encode(value, forKey: .serverContent)
        case .toolCall(let value):
            try container.encode(value, forKey: .toolCall)
        case .toolCallCancellation(let value):
            try container.encode(value, forKey: .toolCallCancellation)
        case .goAway(let value):
            try container.encode(value, forKey: .goAway)
        case .sessionResumptionUpdate(let value):
            try container.encode(value, forKey: .sessionResumptionUpdate)
        }
    }
}
