//
//  ExecutableCode.swift
//  Sandcastle
//
//  Created by Leptos on 2/21/26.
//

import Foundation

/// Code generated by the model that is meant to be executed, and the result returned to the model.
///
/// Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding ``CodeExecutionResult`` will also be generated.
///
/// <https://ai.google.dev/api/caching#ExecutableCode>
struct ExecutableCode: Codable {
    // this declaration is not complete - see documentation above for all fields
}
