//
//  Part.swift
//  Sandcastle
//
//  Created by Leptos on 2/19/26.
//

import Foundation

/// A datatype containing media that is part of a multi-part Content message.
///
/// A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in ``Part/data``.
///
/// A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the ``inlineData`` field is filled with raw bytes.
///
/// <https://ai.google.dev/api/caching#Part>
struct Part {
    enum Data {
        /// Inline text.
        case text(String)
        /// Inline media bytes.
        case inlineData(Blob)
        /// A predicted ``FunctionCall`` returned from the model that contains a string representing the ``FunctionDeclaration/name`` with the arguments and their values.
        case functionCall(FunctionCall)
        /// The result output of a ``FunctionCall`` that contains a string representing the ``FunctionDeclaration/name`` and a structured JSON object containing any output from the function is used as context to the model.
        case functionResponse(FunctionResponse)
        /// URI based data.
        case fileData(FileData)
        /// Code generated by the model that is meant to be executed.
        case executableCode(ExecutableCode)
        /// Result of executing the ``ExecutableCode``.
        case codeExecutionResult(CodeExecutionResult)
    }
    
    enum Metadata {
        /// Video metadata.
        ///
        /// The metadata should only be specified while the video data is presented in `inlineData` or `fileData`.
        case videoMetadata(VideoMetadata)
    }
    
    /// Indicates if the part is thought from the model.
    let thought: Bool?
    /// An opaque signature for the thought so it can be reused in subsequent requests.
    let thoughtSignature: Protobuf.Bytes?
    /// Custom metadata associated with the Part.
    ///
    /// Agents using `genai.Part` as content representation may need to keep track of the additional information.
    /// For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.
    let partMetadata: [String: AnyJson]?
    // (no doc comment)
    let data: Data
    /// Controls extra preprocessing of data.
    let metadata: Metadata?
}

extension Part: Codable {
    enum CodingKeys: String, CodingKey {
        case thought
        case thoughtSignature
        case partMetadata
        
        // data
        case text
        case inlineData
        case functionCall
        case functionResponse
        case fileData
        case executableCode
        case codeExecutionResult
        
        // metadata
        case videoMetadata
    }
    
    init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        self.thought = try container.decodeIfPresent(Bool.self, forKey: .thought)
        self.thoughtSignature = try container.decodeIfPresent(Protobuf.Bytes.self, forKey: .thoughtSignature)
        self.partMetadata = try container.decodeIfPresent([String: AnyJson].self, forKey: .partMetadata)
        
        if let value = try container.decodeIfPresent(String.self, forKey: .text) {
            self.data = .text(value)
        } else if let value = try container.decodeIfPresent(Blob.self, forKey: .inlineData) {
            self.data = .inlineData(value)
        } else if let value = try container.decodeIfPresent(FunctionCall.self, forKey: .functionCall) {
            self.data = .functionCall(value)
        } else if let value = try container.decodeIfPresent(FunctionResponse.self, forKey: .functionResponse) {
            self.data = .functionResponse(value)
        } else if let value = try container.decodeIfPresent(FileData.self, forKey: .fileData) {
            self.data = .fileData(value)
        } else if let value = try container.decodeIfPresent(ExecutableCode.self, forKey: .executableCode) {
            self.data = .executableCode(value)
        } else if let value = try container.decodeIfPresent(CodeExecutionResult.self, forKey: .codeExecutionResult) {
            self.data = .codeExecutionResult(value)
        } else {
            let allKeys: [CodingKeys] = [.text, .inlineData, .functionCall, .functionResponse, .fileData, .executableCode, .codeExecutionResult]
            let keysFormatted = allKeys
                .map { "'\($0.rawValue)'" }
                .joined(separator: ", ")
            throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Expected one of \(keysFormatted)"))
        }
        
        if let value = try container.decodeIfPresent(VideoMetadata.self, forKey: .videoMetadata) {
            self.metadata = .videoMetadata(value)
        } else {
            self.metadata = nil
        }
    }
    
    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encodeIfPresent(thought, forKey: .thought)
        try container.encodeIfPresent(thoughtSignature, forKey: .thoughtSignature)
        try container.encodeIfPresent(partMetadata, forKey: .partMetadata)
        
        switch data {
        case .text(let value):
            try container.encode(value, forKey: .text)
        case .inlineData(let value):
            try container.encode(value, forKey: .inlineData)
        case .functionCall(let value):
            try container.encode(value, forKey: .functionCall)
        case .functionResponse(let value):
            try container.encode(value, forKey: .functionResponse)
        case .fileData(let value):
            try container.encode(value, forKey: .fileData)
        case .executableCode(let value):
            try container.encode(value, forKey: .executableCode)
        case .codeExecutionResult(let value):
            try container.encode(value, forKey: .codeExecutionResult)
        }
        
        switch metadata {
        case .videoMetadata(let value):
            try container.encode(value, forKey: .videoMetadata)
        case .none:
            break // do nothing
        }
    }
}
